- website/data/open-source/projects.yml
---
The OtacilioN/Brasilino library allows programming in Arduino language using commands facilitated in PT-BR
---
> feat: added OtacilioN/Brasilino to oss projects list

- website/data/open-source/maintainers.yml
Maintainer of any projects
---
---
> maintainers: add me (avelino)

- script/website-pr-validation.rb
---
> This PR aims to fix the bug in the website-pr-validation script used to validate the PRs which are made to edit the contents in the website
---
> fix: fixed the method name in website-pr-validation script

- website/data/open-source/maintainers.yml
- website/data/open-source/projects.yml
> Update projects.yml (add react-ape)

- website/data/open-source/projects.yml
From Brazilian developers but also highlight that project name was created based on Rio de Janeiro city 😆 🙏 🇧🇷 
---
---
> Add Rio terminal

- website/data/open-source/projects.yml
> add awesome-go

- website/data/open-source/projects.yml
---
ShellHub is a Brazilian open-source solution that provides secure access to Linux devices, servers, and IoT devices via SSH and Web. It offers features like centralized SSH key management, multi-factor authentication, and session recording. The project is kept up by a team of developers, mostly Brazilians, and has a growing community of users. With the increasing demand for secure remote access solutions, ShellHub can be a valuable addition to the open-source community. By featuring this project on the repository, we can encourage more developers to contribute, use and benefit from the project.
---
> Add ShellHub project

- website/data/open-source/maintainers.yml
---
[Nodejs](https://github.com/nodejs/node/commits?author=RafaelGSS), [Fastify](https://github.com/fastify/fastify/commits?author=RafaelGSS) and many others
---
> Nominate RafaelGSS to maintainers.yml

- website/data/open-source/maintainers.yml
- website/data/open-source/projects.yml
---
This project is from Brazil and it's relevant on the React Native community. It has currently 1.6k stars and it's wide used globally.
https://github.com/RocketChat/Rocket.Chat.ReactNative/
---
> Add RocketChat/Rocket.Chat.ReactNative

- website/data/open-source/maintainers.yml
Following up https://github.com/github/brasil/pull/25
> doc: fix RafaelGSS handle and state

- website/data/open-source/projects.yml
Hi!
I'm adding myself as a maintainer and adding a new category called "Security & Privacy", also I added the first project to this section.
Thanks!
> Added a new category and new projects

- website/data/open-source/maintainers.yml
Hi,
I'm adding myself as a maintainer because my other PR with a personal project has been accepted: https://github.com/github/brasil/pull/31
Thanks.
> New maintainer

- website/data/open-source/maintainers.yml
- [ x] I followed the contributing guidelines: <https://github.com/github/brasil/blob/main/CONTRIBUTING.md>.
- [x ] Adding/updating maintainer/s
---
- [ x] Maintainer's location on their GitHub profile indicates as Brazil
- [ x] Maintainer has approved this PR to be included on the website
expressots/expressots
Adicionando rsaz como mantenedor do expressots/expressots
---
**Please note: we will close your PR without comment if …
> add rsaz as maintainer

- website/data/open-source/maintainers.yml
---
> https://github.com/giggio/node-chromedriver
> Update maintainers.yml, add giggio

- website/data/open-source/projects.yml
---
> it is a significant npm library.
> Update projects.yml, add node-chromedriver

- .github/PULL_REQUEST_TEMPLATE.md
- SECURITY.md
- SUPPORT.md
---
> Este meu pull request sugere traduções de:
> - PR template
> - Security.md 
> - e Support.md 
> 
> Entendo que este projeto a intenção principal é voltado para o público Brasileiro, por isso minha sugestão em português, melhorando a inclusão de mais colegas de nossa profissão a incluirem e movimentar mais facilmente este repo.
---
> :fire: Translate the PR template, security and support to ptbr

- README.md
- website/data/open-source/maintainers.yml
- website/data/open-source/projects.yml
- [ x ] I followed the contributing guidelines: <https://github.com/github/brasil/blob/main/CONTRIBUTING.md>.
- [ x ] Adding/updating open source project/s
- [ x ] Adding/updating maintainer/s
---
- [ x ] The project was built in or receives significant contributions from Brazil
> Web Essentials is a useful tool for computer users, especially those who have just formatted their device or are looking for a list of essential software to have installed on their computer. By offering a list of free and open source software, Web Essentials helps promote an open source culture where users can access quality tools without having to pay for them. Also, the fact that Web Essentials is free and without ads can be considered an advantage over …
> [Pull Request] Maintainers + Projects + README Fixed

- website/data/open-source/projects.yml
---
> é uma biblioteca de gerenciamento de estado para react, que pode ser usada de maneira simples assim como useState e ainda adiciona varias funcionalidades sem a necessidade de contexto o que facilita a introdução de pessoas novas no time e abre um leque de possibilidades de como montar estados globais e é mantida a mais de 2 anos.
---
> Update projects.yml, add re-state

- website/data/open-source/maintainers.yml
- website/data/open-source/projects.yml
add me as maintainer increasing regional diversity of maintainers list 
I'm currently maintaining:
- [Brasilino](https://github.com/OtacilioN/Brasilino)
- [Awesome Hacktoberfest](https://github.com/OtacilioN/awesome-hacktoberfest)
- [Funny Algorithms](https://github.com/ReciHub/FunnyAlgorithms)
---
- [Brasilino](https://github.com/OtacilioN/Brasilino)
- [Awesome Hacktoberfest](https://github.com/OtacilioN/awesome-hacktoberfest-2022)
- [Funny Algorithms](https://github.com/ReciHub/FunnyAlgorithms)
> Por favor, substitua esta linha por uma …
> Add OtacilioN to the list

- website/data/open-source/maintainers.yml
---
https://github.com/cookiecutter/cookiecutter-django
---
> Add Fabio as maintainer of Cookiecutter-django

- website/data/open-source/projects.yml
---
A [Undistro](https://undistro.io/) é uma iniciativa apoiada pela [Getup](https://getup.io/) que cria soluções voltadas para a gestão de ambientes Kubernetes. Por ser uma iniciativa brasileira, adicioná-lo ao repositório do GitHub Brasil fortalece a comunidade de desenvolvedores brasileiros e promove colaboração e inovação, oferecendo, além de estimular o engajamento da comunidade.
> new: feat: add undistro open-source projects

- website/data/open-source/maintainers.yml
- website/data/open-source/projects.yml
---
É um projeto que visa aumentar a acessibilidade digital no Brasil e no mundo através da criação de um base de dados totalmente pública e gratuita de sinais, apoiada por uma Associação e Universidade Estadual. 
O objetivo do projeto é fornecer a base para que qualquer pessoa, organização empresa pública e privada crie e desenvolva tradutores de língua de sinais, assim dimiuindo uma barreira linguística que existe entre a comunidade surda e o resto do mundo.
- https://github.com/folhascadentes/mamao-app
- https://github.com/folhascadentes/mamao-backend
---
**Obs: fecharemos o seu PR sem …
> Add new project and mainteiner

- CONTRIBUTING.md
---
> Este PR possui alterações no arquivo [CONTRIBUTING.md](https://github.com/github/brasil/blob/main/CONTRIBUTING.md) que incluem: 1. Melhorias e correções nos textos e na identação do código. 2. Mudança dos artigos de referência que são linkados na versão português do texto, alterando dos artigos em inglês para versão traduzida dos mesmos.
---
**Obs: fecharemos o seu PR sem comentários se você não marcar as caixas acima e fornecer TODAS as …
> CONTRIBUTING.md small improvements

- website/data/open-source/maintainers.yml
> add some brazilian k8s maintainers

- website/data/open-source/projects.yml
---
O Kubepug foi um projeto que eu criei durante a pandemia, quando estava aprendendo Go e queria fazer algo de útil para a comunidade Kubernetes. Hoje ele é amplamente utilizado por SREs, pessoas desenvolvedoras e até empresas de médio a grande porte para planejar a migração de seus clusters Kubernetes sem impacto.
> Add kubepug to projects

- website/data/open-source/maintainers.yml
---
> https://github.com/timescale/timescaledb
> https://github.com/fabriziomello/pg_toolkit_brazil
> https://github.com/fabriziomello/unique_id
> https://github.com/fabriziomello/pg_normalize_query
> https://github.com/envoyproxy/envoy/ (Code owner of PostgreSQL Proxy - https://github.com/envoyproxy/envoy/blob/cacd32bc9e3285f6eee7efbc3fcb3e7291975055/CODEOWNERS#L355)
> https://github.com/prest/prest (despite I'm commiter I act mostly as a "postgres expert")
---
> Add "fabriziomello" to maintainers.yml

- website/data/open-source/maintainers.yml
---
> - [Ultrasonic](https://github.com/ErickSimoes/Ultrasonic)
> - [Brasilino](https://github.com/OtacilioN/Brasilino)
> - [Funny Algorithms](https://github.com/ReciHub/FunnyAlgorithms)
---
> Add `ErickSimoes` to the maintainer list

- website/data/open-source/projects.yml
Minimalist library for ultrasound module to Arduino.
---
> A Ultrasonic é um projeto de quase 10 anos que fornece uma biblioteca minimalista e fácil de usar para Arduino. O sensor ultrassônico possibilita medir distâncias e, com essa biblioteca, é possível fazer isso consumindo o mínimo de recursos possíveis. Hoje ela é uma das bibliotecas de ultrassom mais populares na plataforma Arduino, e uma das mais relevantes contribuições brasileiras para o movimento maker.
---
> Add `Ultrasonic` Arduino Library to projects list

- website/data/open-source/maintainers.yml
Add daltonmenezes
---
> https://github.com/daltonmenezes/electron-app
https://github.com/daltonmenezes/interprocess
https://github.com/daltonmenezes/aura-theme
https://github.com/daltonmenezes/use-exit-intent
> Add daltonmenezes to the maintainer list

- website/data/open-source/projects.yml
---
Biblioteca de interface com os webservices de Nota Fiscal Eletrônica (NF-e) e Nota Fiscal de Consumidor Eletrônica (NFC-e) da SEFAZ e Receita Federal do Brasil, Nota Fiscal de Serviço Eletrônica (NFS-e) para Prefeituras e Manifesto de Documentos Fiscais Eletrônicos (MDF-e).
Biblioteca escrita na linguagem python mais popular do github, ativa a quase 10 anos e com mais de 30 contribuidores.
---
> add pynfe to projects.yml

- website/data/open-source/projects.yml
---
Dar visibilidade ao trabalho de brasileiros (reconhecidos via stars e traduções) no mundo OSS.
Seguem Alguns:
* https://github.com/leandromoreira/digital_video_introduction
* https://github.com/leandromoreira/ffmpeg-libav-tutorial
* https://github.com/leandromoreira/cdn-up-and-running
* https://github.com/leandromoreira/linux-network-performance-parameters
* https://github.com/leandromoreira/redlock-rb
> Add my own projects

- website/data/open-source/projects.yml
---
> É uma importante lib do [ecossistema ZIO](zio.dev), originalmente criada por [@fwbrasil](https://github.com/fwbrasil)
> add zio-quill to projects

- website/data/open-source/maintainers.yml
- website/data/open-source/projects.yml
---
É um dos mais importantes projetos para comunidade de Clojure do mundo e vem sendo mantido principalmente por um brasileiro.
https://github.com/clojure-lsp
---
> docs: adds ericdallo & clojure-lsp

- website/data/open-source/maintainers.yml
---
kubernetes, helm, sigstore, ko, entre outros
---
> add cpanato to the maintainers list

- website/data/open-source/maintainers.yml
---
- https://github.com/zio/zio-quill (já adicionado ao site [nesse pull request](https://github.com/github/brasil/pull/74))
- https://github.com/zio/zio-protoquill
---
> add juliano to maintainers

- website/data/open-source/projects.yml
---
O brutils-python é uma biblioteca que contém utilitários importantes para os negócios brasileiros. Validação, formatação, geração de números válidos e aleatórios,  de CPF's, CNPJ's, CEP's, placas de carro, entre outros... 
---
> add brutils-python to projects.yml

- website/data/open-source/maintainers.yml
> Adding Vinicius Ventura to maintaners

- website/data/open-source/maintainers.yml
---
> [nix-config](https://github.com/abehidek/nix-config), [hidek.xyz](https://github.com/abehidek/hidek.xyz), [einer](https://github.com/ets-einer/einer), [sandbox](https://github.com/abehidek/sandbox), [monkeydevs.org](https://github.com/monkey-developers/monkeydevs.org) e [monkeynote](https://github.com/monkey-developers/monkeynotes).
---
> add abehidek to maintainers

- website/data/open-source/maintainers.yml
---
> https://github.com/vsouza/awesome-ios
> https://github.com/vsouza/go-gin-boilerplate
> https://github.com/vsouza/awesome-gists
> https://github.com/vsouza/docker-SQS-local
> https://github.com/vsouza/go-kafka-example
> https://github.com/vsouza/GraphQL-handler
> Adicionando Vinicius Souza na lista de contribuidores. Com mais de 1.5k de seguidores no github e somando mais de 45k stars nos projetos, o perfil se enquadra na lista de contribuidores que representam a comunidade brasileira.
---
**Obs: fecharemos o seu PR sem comentários se …
> Added vsouza to maintaners

- website/data/open-source/projects.yml
- [✅] Segui as diretrizes de contribuição: https://github.com/github/brasil/blob/main/CONTRIBUTING.md.
- [✅] Adicionar/atualizar projeto(s) de código aberto
---
- [✅] O projeto foi construído no Brasil ou recebe contribuições significativas do Brasil
- [✅] O projeto possui pelo menos 100 pessoas marcando como favorito (stargazers)
> Diciotech: trata-se de um projeto open source e construído e mantido por pessoas brasileiras para ajudar a entender diversos termos técnicos da nossa área, incluindo principalmente pessoas iniciantes e pessoas que querem entender um pouco mais sobre como funciona a nossa comunicação.
> BotCity Framework Core Python: trata-se de um projeto de Python e open source também construído e mantido por …
> Adicionando dois projetos open source e brasileiros para a página de projetos

- website/data/open-source/maintainers.yml
- website/data/open-source/projects.yml
---
Projeto desenvolvido em Python implementando Domain Notification Pattern o que facilita as validações de dominio. 
https://github.com/fazedordecodigo/PyFlunt
> Add PyFlunt

- website/data/open-source/projects.yml
---
> 🐷 [**Poku**](https://github.com/wellwelwel/poku) é um projeto focado em execução e criação de testes automatizados para **Node.js**, **TypeScript**, **Bun** e **Deno**, abstraindo as complexidades para si e tornando algo que hoje pode ser muitas vezes complexo e até difícil, em um aprendizado leve, simples e até amigável para todos os desenvolvedores.
> 
> No _GIF_ abaixo estão dois exemplos reais, o primeiro usando o _tester_ mais popular atualmente para **Node.js** e em seguida, o [**Poku**](https://github.com/wellwelwel/poku), ambos chegando no mesmo resultado em um simples teste de `"1 é igual a 1"` com **ESM** (`mjs`) puro:
> 
> <img src="https://github.com/wellwelwel/sequelize/assets/46850407/329b4274-6002-49dc- …
> add poku to projects

- website/data/open-source/projects.yml
> Revert "add poku to projects"

- website/data/open-source/projects.yml
---
> O projeto OKE-Free destina-se ao estudo de Kubernetes, utilizando a infraestrutura da Oracle Cloud para implementar um cluster completo, bastante próximo ao cenário "real de produção". O projeto foi criado e está sendo mantido por colaboradores brasileiros, com a participação ativa da comunidade.
---
> Add a project to create a K8s cluster on Oracle

- website/data/open-source/maintainers.yml
---
- https://github.com/phpmyadmin
- https://github.com/php/doc-pt_br
---
> Add MauricioFauth to maintainers.yml

- website/data/open-source/projects.yml
Reverts github/brasil#87 
@vsouza Conforme nossa conversa, por favor, adicione uma licença e reenvie.
> Revert "Update projects.yml"

- website/data/open-source/projects.yml
---
> O Projeto do docker SQS é utilizado amplamente pela comunidade e tem mais de 800k pulls. O Awesome-iOS é a referência mundial de lista de projetos para desenvolvedores iOS e conta com mais de 1k de contributors ao redor do mundo.
---
> Add Docker SQS and Awesome-iOS

- website/data/open-source/maintainers.yml
- website/data/open-source/projects.yml
---
CadZinho é um software de projeto assistido por computador (CAD), um aplicativo desktop voltado para para desenhos técnicos 2D. Ele é desenvolvido por Ezequiel Rabelo de Aguiar, em Belo Horizonte - MG
Cadzinho é livre, portátil e extensível, que pode:
- Abrir, visualizar, criar e modificar nativamente arquivos DXF (padrão DXF "moderno" - versão 2007)
- Gerar arquivos de impressão (PDF, SVG, PS e formatos de imagem)
- Exportar para os formatos G-code e HPGL
- Linguagem de script (linguagem [Lua](https://www.lua.org/) ) para criar macros, ferramentas personalizadas e interface customizada
[https://github.com/zecruel/CadZinho](https://github.com/zecruel/CadZinho)
> Add CadZinho

- website/data/open-source/maintainers.yml
update list of maintainers and fix state list
> fix states list

- website/data/open-source/maintainers.yml
---
https://github.com/Universidade-Livre
---
> Add Camilo and Mateus from Universidade Brasileira Livre

- website/data/open-source/projects.yml
---
É um [template de site pessoal](https://github.com/george-gca/multi-language-al-folio) com suporte a múltiplas línguas, blog, lista de publicações e projetos pessoais. Ele foi criado para ajudar pessoas do meio acadêmico a criar um site pessoal de uma forma simples, mas nada impede que seja usado por pessoas fora dele. Ele possui suporte a vários tipos de conteúdo, como gráficos, mapas, entre outros. Um exemplo de uso pode ser visto [aqui](https://george-gca.github.io/multi-language-al-folio/pt-br/).
> Adicionado template de site pessoal no GitHub

- website/data/open-source/maintainers.yml
---
- 🇧🇷 [**Poku**](https://github.com/wellwelwel/poku) ![NPM Downloads](https://img.shields.io/npm/dy/poku)
- Including, **Poku** was the project that debuted [**Open Source Friday Brasil**](https://www.linkedin.com/events/opensourcefridaybrasilcomweslle7305618122546294807/comments/) series with @pachicodes | **Poku** foi, inclusive, o projeto que estreou o [**Open Source Friday Brasil**](https://www.linkedin.com/events/opensourcefridaybrasilcomweslle7305618122546294807/comments/) com @pachicodes 🎉
- 🇧🇷 [**lru.min**](https://github.com/wellwelwel/lru.min) ![NPM Downloads](https://img.shields.io/npm/dy/lru.min)
- 🇧🇷 [**SVPS**](https://github.com/wellwelwel/svps) ![NPM Downloads](https://img.shields.io/npm/dy/svps)
- 🇧🇷 …
> add `wellwelwel` to maintainers
